# -*- coding: utf-8 -*-
"""VisualisasiData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sV8yXKxxzKYNZVpZ0nVuQYIUWkef7fv6
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv("dataku.csv")
data.head()

data.info()

data['New cases'].unique()

New_case = '71'
data[data['New cases']==New_case]

unique_countries = data[data.Confirmed>0]['Country/Region'].unique()
unique_countries.sort()
unique_countries

country_confirmed_case = []
for i in unique_countries:
  country_confirmed_case.append(data[data.Confirmed>0][data['Country/Region']==i][data['New cases']==New_case].Confirmed.sum())

print(set(zip(unique_countries, country_confirmed_case)))

WHO_region_unique = data['WHO Region'][data.Confirmed>1].unique()
WHO_region_unique

WHO_region_case = []
for i in WHO_region_unique:
  WHO_region_case.append(data[data.Confirmed>0][data['WHO Region']==i][data['New cases']==New_case].Confirmed.sum())

print(set(zip(WHO_region_unique, WHO_region_case)))

nan_indices = []
for i in range(len(WHO_region_unique)):
  if type(WHO_region_unique[i])==float:
    nan_indices.append(i)

WHO_region_unique = list(WHO_region_unique)
province_confirmed_case = list(WHO_region_case)

for i in nan_indices:
  WHO_region_unique.pop(i)
  WHO_region_case.pop(i)

WHO_region_unique

plt.barh(unique_countries, country_confirmed_case)
plt.show()

plt.figure(figsize=(50,40))
plt.barh(WHO_region_unique, WHO_region_case)
plt.show()

plt.figure(figsize=(10,10))
plt.pie(country_confirmed_case)
plt.legend(unique_countries, loc='best')
plt.show()

plt.figure(figsize=(20,20))
plt.pie(WHO_region_case)
plt.legend(WHO_region_unique, loc='best')
plt.show()